version: '3'
services:
  backend:
    container_name: backend
    image: index.docker.io/nfleig/parkpal-backend:latest
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    environment:
      - NODE_ENV
      - PORT
      - DB_HOST
      - FRONTEND_URL
    networks:
      - parkpal
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=parkpaldb
    ports:
      - 5432:5432
    volumes:
      - .dbdata:/var/lib/postgresql/data
    networks:
      - parkpal
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs/certbot/conf:/etc/letsencrypt
      - ./certs/certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    ports:
      - 80:80
      - 443:443
    networks:
      - parkpal
    depends_on:
      - backend
  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: always
    volumes:
      - ./certs/certbot/conf:/etc/letsencrypt
      - ./certs/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - parkpal
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: --interval 30
networks:
  parkpal:
    driver: bridge
